language: erlang
script: "make travis"
otp_release:
  - 18.2
  - 18.0
  - 17.5
  - 17.0
  - R16B03-1
  - R16B
  - R15B03
  - R15B
#before_script: "sudo apt-get --yes --force-yes install libpam0g-dev"
